Repository zalando/postgres-operator, pull requests merged in 2019-05, with the labels that each got.

#534 Use /status subresource instead of plain manifest field
  charts/postgres-operator/templates/clusterrole.yaml
  manifests/operator-service-account-rbac.yaml
  pkg/apis/acid.zalan.do/v1/const.go
  pkg/apis/acid.zalan.do/v1/marshal.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/util.go
  pkg/apis/acid.zalan.do/v1/util_test.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/sync.go
  pkg/controller/util_test.go
  pkg/util/k8sutil/k8sutil.go
Labels: enhancement

#442 Add logical backup
  charts/postgres-operator/templates/clusterrole.yaml
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/developer.md
  docs/reference/cluster_manifest.md
  docs/reference/operator_parameters.md
  docs/user.md
  manifests/complete-postgres-manifest.yaml
  manifests/configmap.yaml
  manifests/minimal-postgres-manifest.yaml
  manifests/operator-service-account-rbac.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/k8sres.go
  pkg/cluster/resources.go
  pkg/cluster/sync.go
  pkg/cluster/util.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
  pkg/util/k8sutil/k8sutil.go
  run_operator_locally.sh
Labels: in-progress, needs review

#561 database.go: remove hardcoded .svc.cluster.local dns suffix
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/reference/operator_parameters.md
  manifests/configmap.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/cluster/database.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: good first issue
