Repository zalando/postgres-operator, pull requests merged in 2020-11, with the labels that each got.

#746 move to apiextensions from v1beta1 to v1
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/crds/postgresqls.yaml
  charts/postgres-operator/crds/postgresteams.yaml
  kubectl-pg/cmd/check.go
  manifests/fake-teams-api.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql.crd.yaml
  manifests/postgresteam.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/controller/util.go
  pkg/util/k8sutil/k8sutil.go
Labels: zalando

#1160 Remove operator checks that prevent PG major version upgrade
  docs/administrator.md
  docs/user.md
  pkg/cluster/cluster.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/sync.go
Labels: enhancement, needs review, zalando

#1202 Update e2e pipeline
  e2e/README.md
  e2e/tests/k8s_api.py
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
Labels: needs review, zalando

#1194 check resize mode on update events
  charts/postgres-operator/templates/clusterrole.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  manifests/configmap.yaml
  manifests/operator-service-account-rbac.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/cluster/cluster.go
  pkg/cluster/sync.go
  pkg/cluster/volumes.go
  pkg/cluster/volumes_test.go
Labels: zalando

#1127 Connection pooler for replica
  charts/postgres-operator/crds/postgresqls.yaml
  docs/reference/cluster_manifest.md
  docs/user.md
  e2e/scripts/watch_objects.sh
  e2e/tests/k8s_api.py
  e2e/tests/test_e2e.py
  manifests/complete-postgres-manifest.yaml
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/cluster/cluster.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/connection_pooler_new_test.go
  pkg/cluster/connection_pooler_test.go
  pkg/cluster/database.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/resources.go
  pkg/cluster/resources_test.go
  pkg/cluster/sync.go
  pkg/cluster/sync_test.go
  pkg/cluster/types.go
  pkg/cluster/util.go
  pkg/controller/postgresql.go
  ui/operator_ui/main.py
Labels: enhancement, zalando

#1215 Use Github.com actions to run tests and e2e tests.
  .github/workflows/run_e2e.yaml
  .travis.yml
  delivery.yaml
Labels: enhancement, zalando

#1212 CRD: preserve unknown fields and add to all category
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/crds/postgresqls.yaml
  charts/postgres-operator/crds/postgresteams.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql.crd.yaml
  manifests/postgresteam.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
Labels: bug, enhancement, zalando

#1213 Fix connection pooler deployment selectors
  e2e/scripts/watch_objects.sh
  e2e/tests/test_e2e.py
  manifests/minimal-fake-pooler-deployment.yaml
  manifests/postgres-operator.yaml
  pkg/cluster/connection_pooler.go
  pkg/cluster/connection_pooler_test.go
Labels: bug, zalando

#1235 raise log level for malformed secrets
  pkg/cluster/sync.go
Labels: enhancement, zalando

#1172 Introduce PGVERSION
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/reference/operator_parameters.md
  e2e/tests/test_e2e.py
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: enhancement, needs review, zalando
