Repository zalando/postgres-operator, pull requests merged in 2020-12, with the labels that each got.

#1242 Support EBS gp2 to gp3 migration on sync for below 1tb volumes
  .github/workflows/run_e2e.yaml
  .github/workflows/run_tests.yaml
  .gitignore
  Makefile
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  delivery.yaml
  docs/reference/operator_parameters.md
  go.mod
  go.sum
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  mocks/mocks.go
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/sync.go
  pkg/cluster/volumes.go
  pkg/cluster/volumes_test.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
  pkg/util/volumes/ebs.go
  pkg/util/volumes/volumes.go
Labels: enhancement, zalando

#1236 Support inherited annotations for all major objects
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/reference/operator_parameters.md
  e2e/tests/k8s_api.py
  e2e/tests/test_e2e.py
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/k8sres.go
  pkg/cluster/sync.go
  pkg/cluster/util.go
  pkg/cluster/util_test.go
  pkg/cluster/volumes_test.go
  pkg/controller/operator_config.go
  pkg/controller/postgresql.go
  pkg/controller/util.go
  pkg/util/config/config.go
  pkg/util/k8sutil/k8sutil.go
Labels: enhancement, zalando

#1250 Fix function name in test
  pkg/cluster/volumes_test.go
Labels: bug, zalando

#1173 Add ability to upload logical backup to gcs
  docker/logical-backup/Dockerfile
  docker/logical-backup/dump.sh
  docs/reference/operator_parameters.md
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/cluster/k8sres.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: enhancement

#1256 Sync sts at pgversion upgrade
  pkg/cluster/cluster.go
Labels: bug

#1166 Add node affinity support
  charts/postgres-operator/crds/postgresqls.yaml
  docs/user.md
  e2e/tests/test_e2e.py
  manifests/complete-postgres-manifest.yaml
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
Labels: enhancement

#1257 Initial commit for new 1.6 release with Postgres 13 support.
  .github/workflows/run_e2e.yaml
  .github/workflows/run_tests.yaml
  CODEOWNERS
  MAINTAINERS
  README.md
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/templates/clusterrole.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  delivery.yaml
  docs/administrator.md
  docs/developer.md
  docs/gsoc-2019/ideas.md
  docs/reference/operator_parameters.md
  docs/user.md
  e2e/run.sh
  e2e/tests/test_e2e.py
  manifests/complete-postgres-manifest.yaml
  manifests/configmap.yaml
  manifests/minimal-postgres-manifest.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  mkdocs.yml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/cluster/connection_pooler_test.go
  pkg/cluster/k8sres_test.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
  ui/manifests/deployment.yaml
  ui/operator_ui/main.py
Labels: in-progress, zalando
