Repository zalando/postgres-operator, pull requests merged in 2020-10, with the labels that each got.

#1156 update kind
  e2e/Makefile
Labels: zalando

#1169 Readiness probe
  pkg/cluster/k8sres.go
Labels: bug, zalando

#1171 Lookup function installation
  e2e/exec.sh
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
  pkg/cluster/database.go
  pkg/cluster/sync.go
Labels: bug, zalando

#1164 Remove repeated initialization of Pod ServiceAccount
  pkg/controller/controller.go
Labels: bug

#1175 add maxLength constraint for CRD
  charts/postgres-operator/crds/postgresqls.yaml
  docs/user.md
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
Labels: zalando

#1180 End 2 End tests speedup
  Makefile
  e2e/Dockerfile
  e2e/README.md
  e2e/exec_into_env.sh
  e2e/run.sh
  e2e/scripts/cleanup.sh
  e2e/scripts/get_logs.sh
  e2e/scripts/watch_objects.sh
  e2e/tests/k8s_api.py
  e2e/tests/test_e2e.py
  manifests/postgres-operator.yaml
  pkg/cluster/cluster.go
  pkg/cluster/database.go
  pkg/cluster/k8sres.go
  pkg/cluster/pod.go
  pkg/cluster/resources.go
  pkg/cluster/sync.go
  pkg/cluster/util.go
  pkg/controller/controller.go
  pkg/controller/node.go
  pkg/controller/postgresql.go
  pkg/util/config/config.go
  pkg/util/nicediff/diff.go
  pkg/util/util_test.go
Labels: enhancement, in-progress, zalando

#1165 PostgresTeam CRD for advanced team management
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/crds/postgresteams.yaml
  charts/postgres-operator/templates/clusterrole.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/reference/operator_parameters.md
  docs/user.md
  manifests/configmap.yaml
  manifests/custom-team-membership.yaml
  manifests/operator-service-account-rbac.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  manifests/postgresteam.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/postgres_team_type.go
  pkg/apis/acid.zalan.do/v1/register.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/util.go
  pkg/controller/controller.go
  pkg/controller/operator_config.go
  pkg/controller/util.go
  pkg/generated/clientset/versioned/typed/acid.zalan.do/v1/acid.zalan.do_client.go
  pkg/generated/clientset/versioned/typed/acid.zalan.do/v1/fake/fake_acid.zalan.do_client.go
  pkg/generated/clientset/versioned/typed/acid.zalan.do/v1/fake/fake_postgresteam.go
  pkg/generated/clientset/versioned/typed/acid.zalan.do/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/acid.zalan.do/v1/postgresteam.go
  pkg/generated/informers/externalversions/acid.zalan.do/v1/interface.go
  pkg/generated/informers/externalversions/acid.zalan.do/v1/postgresteam.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/listers/acid.zalan.do/v1/expansion_generated.go
  pkg/generated/listers/acid.zalan.do/v1/postgresteam.go
  pkg/teams/postgres_team.go
  pkg/teams/postgres_team_test.go
  pkg/util/config/config.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: enhancement, in-progress, zalando

#1159 Refactor connection pooler
  pkg/cluster/cluster.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/connection_pooler_test.go
  pkg/cluster/database.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/resources.go
  pkg/cluster/resources_test.go
  pkg/cluster/sync.go
  pkg/cluster/sync_test.go
  pkg/cluster/types.go
  pkg/cluster/util.go
Labels: enhancement, zalando

#1188 Make failure in retry a warning not an error.
  pkg/cluster/database.go
  pkg/controller/postgresql.go
Labels: enhancement, zalando
