Repository zalando/postgres-operator, pull requests merged in 2020-04, with the labels that each got.

#901 Fix val docs
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/reference/cluster_manifest.md
  docs/user.md
  manifests/complete-postgres-manifest.yaml
Labels: bug

#906 Prevent superuser from being a connection pool user
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/resources.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: bug, zalando

#903 Re-create pods only if all replicas are running
  .gitignore
  e2e/tests/test_e2e.py
  pkg/cluster/pod.go
  pkg/util/patroni/patroni.go
Labels: bug, zalando

#933 fix typo in additionalVolume struct
  manifests/complete-postgres-manifest.yaml
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
Labels: bug

#939 fix params in function call in tests
  pkg/cluster/k8sres_test.go
Labels: bug

#859 Lazy upgrade of the Spilo image
  Makefile
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/reference/operator_parameters.md
  e2e/Makefile
  e2e/tests/test_e2e.py
  go.mod
  go.sum
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/cluster/cluster.go
  pkg/cluster/sync.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: enhancement, zalando

#843 Bootstrapped databases with best practice role setup
  charts/postgres-operator/crds/postgresqls.yaml
  docs/user.md
  manifests/complete-postgres-manifest.yaml
  manifests/minimal-postgres-manifest.yaml
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/database.go
  pkg/cluster/k8sres.go
  pkg/cluster/sync.go
  pkg/controller/types.go
  pkg/spec/types.go
  pkg/util/constants/roles.go
  pkg/util/users/users.go
Labels: zalando
