Repository zalando/postgres-operator, pull requests merged in 2020-08, with the labels that each got.

#1065 set search_path for default roles
  pkg/cluster/cluster.go
  pkg/util/constants/roles.go
  pkg/util/users/users.go
Labels: zalando

#1069 allow delete only if annotations meet configured criteria
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/reference/operator_parameters.md
  e2e/requirements.txt
  e2e/tests/test_e2e.py
  manifests/complete-postgres-manifest.yaml
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/controller/controller.go
  pkg/controller/operator_config.go
  pkg/controller/postgresql.go
  pkg/controller/postgresql_test.go
  pkg/util/config/config.go
Labels: needs review, zalando

#1128 Fix omitempty of attributes of PostgresSpec in postgresql_type.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
Labels: bug
