Repository zalando/postgres-operator, pull requests merged in 2021-06, with the labels that each got.

#1224 Keep single values.yaml in operator chart while supporting ConfigMap & CRD
  charts/postgres-operator/templates/_helpers.tpl
  charts/postgres-operator/templates/configmap.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/developer.md
  docs/quickstart.md
Labels: enhancement

#1490 Create cross namespace secrets
  charts/postgres-operator/crds/postgresqls.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/reference/operator_parameters.md
  docs/user.md
  e2e/tests/k8s_api.py
  e2e/tests/test_e2e.py
  manifests/complete-postgres-manifest.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/k8sres.go
  pkg/cluster/resources.go
  pkg/cluster/sync.go
  pkg/spec/types.go
Labels: zalando

#1103 restart instances via rest api instead of recreating pods, fixes bug with being unable to decrease some values, like max_connections
  docs/administrator.md
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/sync.go
  pkg/util/patroni/patroni.go
Labels: enhancement

#1510 Add basic retry around switchover
  pkg/cluster/pod.go
Labels: enhancement, zalando

#1512 define default access privileges for default users too
  docs/user.md
  pkg/cluster/database.go
  pkg/cluster/sync.go
Labels: zalando
