Repository zalando/postgres-operator, pull requests merged in 2021-02, with the labels that each got.

#1340 Fix volume sync order.
  pkg/cluster/sync.go
Labels: bug, zalando

#1349 making pgTeamMap a pointer
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
  pkg/cluster/util.go
  pkg/controller/controller.go
  pkg/controller/util.go
  pkg/teams/postgres_team.go
  pkg/teams/postgres_team_test.go
Labels: bug, zalando

#1367 bump to v1.6.1
  .github/ISSUE_TEMPLATE/postgres-operator-issue-template.md
  README.md
  charts/postgres-operator-ui/Chart.yaml
  charts/postgres-operator-ui/index.yaml
  charts/postgres-operator-ui/postgres-operator-ui-1.6.0.tgz
  charts/postgres-operator-ui/postgres-operator-ui-1.6.1.tgz
  charts/postgres-operator-ui/values.yaml
  charts/postgres-operator/Chart.yaml
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/index.yaml
  charts/postgres-operator/postgres-operator-1.6.0.tgz
  charts/postgres-operator/postgres-operator-1.6.1.tgz
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/reference/operator_parameters.md
  docs/user.md
  manifests/complete-postgres-manifest.yaml
  manifests/configmap.yaml
  manifests/minimal-fake-pooler-deployment.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgres-operator.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: zalando

#1372 Support major version upgrade via manifest and global upgrades via min version
  e2e/tests/test_e2e.py
  manifests/configmap.yaml
  manifests/minimal-postgres-manifest-12.yaml
  pkg/cluster/cluster.go
  pkg/cluster/k8sres.go
  pkg/cluster/majorversionupgrade.go
  pkg/cluster/pod.go
  pkg/cluster/sync.go
  pkg/controller/postgresql.go
  pkg/controller/util_test.go
  pkg/util/config/config.go
  pkg/util/httpclient/httpclient.go
  pkg/util/patroni/patroni.go
  pkg/util/patroni/patroni_test.go
Labels: zalando

#1341 Improve rolling upgrades and rolling upgrade continue
  e2e/scripts/watch_objects.sh
  e2e/tests/k8s_api.py
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
  pkg/cluster/k8sres.go
  pkg/cluster/pod.go
  pkg/cluster/resources.go
  pkg/cluster/sync.go
Labels: enhancement, zalando
