Repository zalando/postgres-operator, pull requests merged in 2021-01, with the labels that each got.

#1287 add a prefix for the name of a logical backup job
  charts/postgres-operator/values.yaml
  docs/reference/operator_parameters.md
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/cluster/k8sres.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: enhancement, zalando

#1297 [UI] on read_pods filter only spilo pods
  ui/operator_ui/spiloutils.py
Labels: bug

#1293 wrap getting Patroni state into retry
  pkg/cluster/pod.go
Labels: enhancement, zalando

#1274 Avoid syncing when possible
  e2e/README.md
  e2e/tests/test_e2e.py
  pkg/cluster/connection_pooler.go
  pkg/cluster/k8sres.go
Labels: enhancement, zalando

#1314 allow additional members from other teams
  pkg/cluster/util.go
Labels: bug

#1301 Use fake client for connection pooler
  pkg/cluster/connection_pooler.go
  pkg/cluster/connection_pooler_test.go
Labels: enhancement, zalando

#1261 Full AWS gp3 support for iops and througput config.
  charts/postgres-operator/crds/postgresqls.yaml
  docs/developer.md
  docs/reference/cluster_manifest.md
  docs/reference/operator_parameters.md
  go.mod
  go.sum
  manifests/complete-postgres-manifest.yaml
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/cluster/sync.go
  pkg/cluster/volumes.go
  pkg/cluster/volumes_test.go
  pkg/util/volumes/ebs.go
  pkg/util/volumes/volumes.go
Labels: enhancement, zalando

#1329 Update go.sum
  go.sum
Labels: zalando

#1336 configurable container capabilities
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/values-crd.yaml
  charts/postgres-operator/values.yaml
  docs/reference/operator_parameters.md
  e2e/tests/k8s_api.py
  e2e/tests/test_e2e.py
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: zalando
