Repository zalando/postgres-operator, pull requests merged in 2022-03, with the labels that each got.

#1799 LoadBalancer toggles for master and replica pooler pods
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/crds/postgresqls.yaml
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/reference/cluster_manifest.md
  docs/reference/operator_parameters.md
  e2e/tests/test_e2e.py
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster_test.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/connection_pooler_test.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/resources.go
  pkg/cluster/sync.go
  pkg/cluster/util_test.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: zalando

#1803 Patroni API timeout
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/values.yaml
  docs/reference/operator_parameters.md
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/cluster/pod.go
  pkg/cluster/pod_test.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: zalando

#1811 Pooler sync fix
  e2e/tests/test_e2e.py
  pkg/cluster/connection_pooler.go
  pkg/cluster/k8sres.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
Labels: bug, zalando

#1805 grant db owners to cron_admin
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/values.yaml
  docs/reference/operator_parameters.md
  e2e/tests/test_e2e.py
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/k8sres.go
  pkg/controller/operator_config.go
  pkg/spec/types.go
  pkg/util/config/config.go
  pkg/util/users/users.go
Labels: zalando

#1817 fix comparison of event stream array
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/apis/zalando.org/v1/fabriceventstream.go
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
  pkg/util/k8sutil/k8sutil.go
Labels: zalando

#1822 refactor GenerateResourceRequirements and provide unit tests
  charts/postgres-operator/crds/postgresqls.yaml
  docs/reference/cluster_manifest.md
  docs/reference/operator_parameters.md
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/sync.go
  pkg/cluster/util.go
Labels: bug, zalando

#1824 [UI] support Postgres version, pod resource changes and IOPS + throughput config options
  ui/app/src/edit.tag.pug
  ui/app/src/help-general.tag.pug
  ui/app/src/new.tag.pug
  ui/app/src/postgresqls.tag.pug
  ui/manifests/deployment.yaml
  ui/operator_ui/main.py
  ui/run_local.sh
Labels: zalando

#1831 Fix deletion of event streams resources
  pkg/cluster/cluster.go
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
Labels: bug

#1833 add chapter about restoring in place
  docs/user.md
  manifests/complete-postgres-manifest.yaml
Labels: documentation
