Repository zalando/postgres-operator, pull requests merged in 2024-02, with the labels that each got.

#2499 Feat: add flags for podPriorityClassName to support external priorityclasses
  charts/postgres-operator/templates/_helpers.tpl
  charts/postgres-operator/templates/configmap.yaml
  charts/postgres-operator/templates/operatorconfiguration.yaml
  charts/postgres-operator/templates/postgres-pod-priority-class.yaml
  charts/postgres-operator/values.yaml
Labels: Helm User

#2535 patch event stream CRD instead of update
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
Labels: bug

#2538 do not block delete because of emtpy child resources
  pkg/cluster/resources.go
Labels: bug

#2546 update spec when updating status
  pkg/cluster/cluster.go
  pkg/cluster/sync.go
  pkg/util/k8sutil/k8sutil.go
Labels: bug

#2549 change username in secret when switching rotation mode
  pkg/cluster/sync.go
  pkg/cluster/sync_test.go
Labels: enhancement
