Repository zalando/postgres-operator, pull requests merged in 2024-08, with the labels that each got.

#2704 stream: slot and FES should not be created if the publication creation fails
  e2e/tests/test_e2e.py
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
Labels: bugfix

#2671 feat: Add extraEnvs to operator helm chart
  charts/postgres-operator/templates/deployment.yaml
  charts/postgres-operator/values.yaml
Labels: Helm User, minor

#2688 Feat: enable owner references
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/templates/clusterrole.yaml
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/reference/operator_parameters.md
  e2e/tests/test_e2e.py
  manifests/configmap.yaml
  manifests/operator-service-account-rbac-openshift.yaml
  manifests/operator-service-account-rbac.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/connection_pooler_test.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/resources.go
  pkg/cluster/streams.go
  pkg/cluster/sync.go
  pkg/cluster/util.go
  pkg/cluster/volumes.go
  pkg/controller/operator_config.go
  pkg/controller/postgresql.go
  pkg/util/config/config.go
Labels: minor

#2723 extend inherited annotations unit test to include logical backup cron job
  pkg/cluster/cluster.go
  pkg/cluster/util_test.go
Labels: minor

#2713 sync all resources to cluster fields
  docs/administrator.md
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/k8sres.go
  pkg/cluster/resources.go
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
  pkg/cluster/sync.go
  pkg/cluster/types.go
  pkg/cluster/util_test.go
Labels: minor

#2715 fix linter issues
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/cluster/cluster.go
  pkg/cluster/exec.go
  pkg/cluster/k8sres.go
  pkg/cluster/util.go
  pkg/controller/util.go
  pkg/util/util.go
Labels: minor

#2728 fix sync streams and add diffs for annotations and owner references
  pkg/cluster/majorversionupgrade.go
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
  pkg/cluster/sync.go
  pkg/cluster/util.go
  pkg/cluster/util_test.go
Labels: bugfix

#2731 MaintenanceWindow CRD validation fix
  charts/postgres-operator/crds/postgresqls.yaml
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/util_test.go
Labels: bugfix

#2732 fix: add secret only when not in secret file
  pkg/cluster/k8sres.go
Labels: bugfix

#2738 align sync and update logs
  pkg/cluster/cluster.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/database.go
  pkg/cluster/majorversionupgrade.go
  pkg/cluster/pod.go
  pkg/cluster/resources.go
  pkg/cluster/streams.go
  pkg/cluster/sync.go
  pkg/cluster/util.go
  pkg/cluster/volumes.go
  pkg/controller/postgresql.go
Labels: minor

#2739 reflect linter feedback, remove unused argumnents and redundant type from arrays
  pkg/cluster/cluster_test.go
  pkg/cluster/connection_pooler_test.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
  pkg/cluster/sync_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/util/k8sutil/k8sutil.go
Labels: minor

#2740 update K8s version and reflect necessary changes
  Makefile
  go.mod
  go.sum
  kubectl-pg/go.mod
  kubectl-pg/go.sum
  pkg/cluster/k8sres.go
  pkg/cluster/volumes_test.go
Labels: minor

#2727 Implement major upgrade result annotations
  docs/administrator.md
  e2e/tests/test_e2e.py
  pkg/cluster/majorversionupgrade.go
Labels: enhancement, minor
