Repository zalando/postgres-operator, pull requests merged in 2024-10, with the labels that each got.

#2772 Add major upgrade prechecks
  go.mod
  go.sum
  pkg/cluster/majorversionupgrade.go
Labels: enhancement, minor

#2775 Skip major upgrade for standby clusters with warning
  pkg/cluster/majorversionupgrade.go
Labels: bugfix

#2774 quote admin user to allow names with special characters
  pkg/util/users/users.go
Labels: bugfix

#2762 update clusterrole.yaml
  charts/postgres-operator/templates/clusterrole.yaml
Labels: minor, bugfix

#2783 fix(postgres-operator/deployment): Set 'nindent' to 8 for 'extraEnvs'
  charts/postgres-operator/Chart.yaml
  charts/postgres-operator/templates/deployment.yaml
Labels: bugfix

#2785 add cluster field for PVCs
  docs/reference/operator_parameters.md
  pkg/cluster/cluster.go
  pkg/cluster/resources.go
  pkg/cluster/volumes.go
  pkg/cluster/volumes_test.go
Labels: minor
