Repository zalando/postgres-operator, pull requests merged in 2024-12, with the labels that each got.

#2818 Integrate spilo with Patroni 4
  pkg/cluster/majorversionupgrade.go
Labels: major

#2737 remove streams delete and extend unit tests
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
Labels: minor

#2817 add resource annotation and ignore recovery type
  charts/postgres-operator/crds/postgresqls.yaml
  docs/reference/cluster_manifest.md
  manifests/postgresql.crd.yaml
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
  pkg/util/constants/streams.go
Labels: minor

#2803 do not use extra labels to list stream CRDs
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
Labels: bugfix

#2820 fix comparing stream annotations and improve unit test
  e2e/tests/test_e2e.py
  pkg/cluster/streams.go
  pkg/cluster/streams_test.go
Labels: bugfix

#2677 Add support for EBS CSI Driver
  .gitignore
  charts/postgres-operator/templates/clusterrole.yaml
  pkg/cluster/volumes.go
  pkg/cluster/volumes_test.go
  pkg/util/constants/aws.go
  pkg/util/volumes/ebs.go
  pkg/util/volumes/ebs_test.go
Labels: minor

#2708 fix: replicaCount not being respect
  charts/postgres-operator-ui/templates/deployment.yaml
Labels: Helm User, minor

#2822 fix flaky stream comparison unit test of retruned errors
  pkg/cluster/streams_test.go
Labels: bugfix

#2773 Add support for pg17 and remove pg12
  .github/workflows/run_tests.yaml
  README.md
  charts/postgres-operator-ui/templates/deployment.yaml
  charts/postgres-operator/crds/operatorconfigurations.yaml
  charts/postgres-operator/crds/postgresqls.yaml
  charts/postgres-operator/values.yaml
  docs/administrator.md
  docs/reference/cluster_manifest.md
  docs/reference/operator_parameters.md
  docs/user.md
  e2e/Makefile
  e2e/run.sh
  e2e/tests/test_e2e.py
  logical-backup/Dockerfile
  manifests/complete-postgres-manifest.yaml
  manifests/configmap.yaml
  manifests/minimal-postgres-lowest-version-manifest.yaml
  manifests/minimal-postgres-manifest.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgresql-operator-default-configuration.yaml
  manifests/postgresql.crd.yaml
  manifests/standby-manifest.yaml
  pkg/apis/acid.zalan.do/v1/crds.go
  pkg/apis/acid.zalan.do/v1/operator_configuration_type.go
  pkg/apis/acid.zalan.do/v1/util_test.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/majorversionupgrade.go
  pkg/controller/operator_config.go
  pkg/util/config/config.go
  ui/manifests/deployment.yaml
  ui/operator_ui/main.py
  ui/operator_ui/spiloutils.py
  ui/run_local.sh
Labels: major

#2667 Add abitility to set QPS and Burst limits for api client
  cmd/main.go
  pkg/spec/types.go
Labels: minor

#2814 Fix deployment extraEnvs indentation in operator chart
  charts/postgres-operator/templates/deployment.yaml
Labels: minor

#2449 Feat: Support Running Sidecar with a Command.
  pkg/apis/acid.zalan.do/v1/postgresql_type.go
  pkg/cluster/k8sres.go
Labels: minor

#2824 bump to go 1.23.4
  .github/workflows/publish_ghcr_image.yaml
  .github/workflows/run_e2e.yaml
  .github/workflows/run_tests.yaml
  Makefile
  README.md
  docker/DebugDockerfile
  docker/Dockerfile
  docker/build_operator.sh
  docs/developer.md
  go.mod
  kubectl-pg/go.mod
Labels: minor

#2825 add sidecar command examples and update codegen
  docs/administrator.md
  docs/user.md
  pkg/apis/acid.zalan.do/v1/zz_generated.deepcopy.go
Labels: bugfix

#2777 manifests/minimal-master-replica-svcmonitor.yaml: Update postgres-exporter image
  manifests/minimal-master-replica-svcmonitor.yaml
Labels: minor

#2827 bump operator to 1.14.0
  charts/postgres-operator-ui/Chart.yaml
  charts/postgres-operator-ui/index.yaml
  charts/postgres-operator-ui/postgres-operator-ui-1.14.0.tgz
  charts/postgres-operator-ui/values.yaml
  charts/postgres-operator/Chart.yaml
  charts/postgres-operator/index.yaml
  charts/postgres-operator/postgres-operator-1.14.0.tgz
  charts/postgres-operator/values.yaml
  manifests/configmap.yaml
  manifests/operatorconfiguration.crd.yaml
  manifests/postgres-operator.yaml
  manifests/postgresql-operator-default-configuration.yaml
  pkg/controller/operator_config.go
  pkg/util/config/config.go
  ui/app/package.json
  ui/manifests/deployment.yaml
Labels: major
