Repository zalando/postgres-operator, pull requests merged in 2025-01, with the labels that each got.

#2829 Update logical backup docker image
  charts/postgres-operator/values.yaml
Labels: bugfix

#2810 Extend MaintenanceWindows parameter usage
  docs/administrator.md
  docs/reference/cluster_manifest.md
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/majorversionupgrade.go
  pkg/cluster/resources.go
  pkg/cluster/sync.go
  pkg/cluster/util.go
  pkg/cluster/util_test.go
  pkg/util/patroni/patroni.go
Labels: major

#2842 Only check maintenance window for upgrade after pg version recheck
  pkg/cluster/majorversionupgrade.go
Labels: minor

#2849 Partially revert #2810
  docs/administrator.md
  docs/reference/cluster_manifest.md
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
  pkg/cluster/pod.go
  pkg/cluster/sync.go
Labels: architectural

#2826 Ensure podAnnotations are removed from pods if reset in the config
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/connection_pooler.go
  pkg/cluster/resources.go
  pkg/cluster/streams.go
  pkg/cluster/sync.go
  pkg/cluster/sync_test.go
  pkg/cluster/util_test.go
  pkg/cluster/volumes.go
Labels: bugfix

#2830 Critical operation PDB
  docs/administrator.md
  docs/quickstart.md
  docs/reference/operator_parameters.md
  e2e/tests/test_e2e.py
  pkg/cluster/cluster.go
  pkg/cluster/k8sres.go
  pkg/cluster/k8sres_test.go
  pkg/cluster/resources.go
  pkg/cluster/sync.go
  pkg/cluster/types.go
  pkg/cluster/util_test.go
Labels: architectural

#2844 Protect Pods from disruptions during upgrades
  pkg/cluster/majorversionupgrade.go
Labels: architectural
